"""add db pengumuman

Revision ID: 1500e835d1b2
Revises: 860c2fd7b3fc
Create Date: 2025-03-06 22:15:57.808445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1500e835d1b2'
down_revision = '860c2fd7b3fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pengumuman',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('judul', sa.String(length=50), nullable=False),
    sa.Column('isi', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('config_props', schema=None) as batch_op:
        batch_op.drop_constraint('config_props_value_key', type_='unique')

    with op.batch_alter_table('harga_gaji', schema=None) as batch_op:
        batch_op.drop_constraint('harga_gaji_value_key', type_='unique')

    with op.batch_alter_table('kuota_cuti', schema=None) as batch_op:
        batch_op.drop_constraint('kuota_cuti_value_key', type_='unique')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=False))
        batch_op.drop_constraint('users_name_key', type_='unique')
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('users_name_key', ['name'])
        batch_op.drop_column('username')

    with op.batch_alter_table('kuota_cuti', schema=None) as batch_op:
        batch_op.create_unique_constraint('kuota_cuti_value_key', ['value'])

    with op.batch_alter_table('harga_gaji', schema=None) as batch_op:
        batch_op.create_unique_constraint('harga_gaji_value_key', ['value'])

    with op.batch_alter_table('config_props', schema=None) as batch_op:
        batch_op.create_unique_constraint('config_props_value_key', ['value'])

    op.drop_table('pengumuman')
    # ### end Alembic commands ###
