"""remove field in data karyawan and data kontak

Revision ID: 40533fc0d083
Revises: 10214f195838
Create Date: 2025-05-13 20:04:37.446983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40533fc0d083'
down_revision = '10214f195838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_karyawan', schema=None) as batch_op:
        batch_op.drop_column('lokasi_kerja')

    with op.batch_alter_table('data_kontak', schema=None) as batch_op:
        batch_op.drop_column('kota_kabupaten')
        batch_op.drop_column('provinsi')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_kontak', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provinsi', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('kota_kabupaten', sa.VARCHAR(length=100), autoincrement=False, nullable=False))

    with op.batch_alter_table('data_karyawan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lokasi_kerja', sa.VARCHAR(length=150), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
