"""refactor db lokasi

Revision ID: 603575939a4b
Revises: c70e78ee621a
Create Date: 2025-03-09 17:26:36.857131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '603575939a4b'
down_revision = 'c70e78ee621a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lokasi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=False))
        batch_op.drop_column('nama')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lokasi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nama', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
