version: '3.8'

services:
  db:
    image: postgres:16.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      # Variabel ini sekarang diambil dari file .env
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 run:app
    volumes:
      - .:/app
      - uploads_volume:/app/uploads
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - FLASK_APP=run.py
      - FLASK_ENV=${FLASK_ENV}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      - db

volumes:
  postgres_data:
  uploads_volume: