"""add user id in approval and delete table approval kehadiran

Revision ID: 01b188861879
Revises: 766c855fb55a
Create Date: 2025-06-14 21:21:26.886438

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '01b188861879'
down_revision = '766c855fb55a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('approval_kehadiran')
    with op.batch_alter_table('approval_izin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.UUID(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('approval_koreksi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.UUID(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('approval_lembur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.UUID(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('approval_reimburse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.UUID(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approval_reimburse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('approval_lembur', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('approval_koreksi', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('approval_izin', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    op.create_table('approval_kehadiran',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('approval_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('absensi_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['absensi_id'], ['absensi.id'], name=op.f('approval_kehadiran_absensi_id_fkey')),
    sa.ForeignKeyConstraint(['approval_user_id'], ['users.id'], name=op.f('approval_kehadiran_approval_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('approval_kehadiran_pkey'))
    )
    # ### end Alembic commands ###
