"""add kalkulasi rincian gaji

Revision ID: 046396b4b40e
Revises: e67687b0c757
Create Date: 2025-08-16 18:50:50.867576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '046396b4b40e'
down_revision = 'e67687b0c757'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('riwayat_penggajian_rincian', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nilai_a', sa.Numeric(precision=15, scale=2), nullable=False))
        batch_op.add_column(sa.Column('nilai_b', sa.Numeric(precision=15, scale=2), nullable=False))
        batch_op.add_column(sa.Column('operasi', sa.String(length=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('riwayat_penggajian_rincian', schema=None) as batch_op:
        batch_op.drop_column('operasi')
        batch_op.drop_column('nilai_b')
        batch_op.drop_column('nilai_a')

    # ### end Alembic commands ###
