"""detail approval koreksi

Revision ID: 0583721a4231
Revises: a4d2ed1fe4c8
Create Date: 2025-06-14 22:39:19.263632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0583721a4231'
down_revision = 'a4d2ed1fe4c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detail_approval_koreksi',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('approval_koreksi_id', sa.UUID(), nullable=False),
    sa.Column('detail_absensi_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['approval_koreksi_id'], ['approval_koreksi.id'], ),
    sa.ForeignKeyConstraint(['detail_absensi_id'], ['detail_absensi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_koreksi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('absensi_id', sa.UUID(), nullable=False))
        batch_op.drop_constraint(batch_op.f('approval_koreksi_detail_absensi_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'absensi', ['absensi_id'], ['id'])
        batch_op.drop_column('detail_absensi_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approval_koreksi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detail_absensi_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('approval_koreksi_detail_absensi_id_fkey'), 'detail_absensi', ['detail_absensi_id'], ['id'])
        batch_op.drop_column('absensi_id')

    op.drop_table('detail_approval_koreksi')
    # ### end Alembic commands ###
