"""add field laporan in kode perhitungan

Revision ID: 075f83ce0a0e
Revises: 37cb20bd23b1
Create Date: 2025-08-13 18:25:06.742627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '075f83ce0a0e'
down_revision = '37cb20bd23b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kode_perhitungan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field_laporan', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kode_perhitungan', schema=None) as batch_op:
        batch_op.drop_column('field_laporan')

    # ### end Alembic commands ###
