"""change nip 16 to 8

Revision ID: 10214f195838
Revises: e63a93e85c4c
Create Date: 2025-05-07 20:14:12.174067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10214f195838'
down_revision = 'e63a93e85c4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_karyawan', schema=None) as batch_op:
        batch_op.alter_column('nip',
               existing_type=sa.VARCHAR(length=18),
               type_=sa.String(length=8),
               existing_nullable=False)

    with op.batch_alter_table('data_kontak', schema=None) as batch_op:
        batch_op.drop_column('negara')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_kontak', schema=None) as batch_op:
        batch_op.add_column(sa.Column('negara', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    with op.batch_alter_table('data_karyawan', schema=None) as batch_op:
        batch_op.alter_column('nip',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=18),
               existing_nullable=False)

    # ### end Alembic commands ###
