"""table gaji dan jabatan

Revision ID: 1655e5d9b267
Revises: 782d66796e34
Create Date: 2025-04-21 21:44:53.832141

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1655e5d9b267'
down_revision = '782d66796e34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grup_gaji',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('grup_kode', sa.String(length=5), nullable=False),
    sa.Column('grup_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grup_kode')
    )
    op.create_table('jabatan',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nama', sa.String(length=50), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['jabatan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('komponen_gaji',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kom_kode', sa.String(length=5), nullable=False),
    sa.Column('kom_name', sa.String(length=100), nullable=False),
    sa.Column('no_urut', sa.SmallInteger(), nullable=False),
    sa.Column('tipe', sa.Enum('TUNJANGAN', 'POTONGAN', name='tipe_kom_gaji'), nullable=False),
    sa.Column('hitung', sa.Enum('HARIAN', 'PERIODE', name='hitung_kom_gaji'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detail_jadwal_kerja',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hari', sa.Enum('SENIN', 'SELASA', 'RABU', 'KAMIS', 'JUMAT', 'SABTU', 'MINGGU', name='hari'), nullable=False),
    sa.Column('time_in', sa.Time(), nullable=False),
    sa.Column('time_out', sa.Time(), nullable=False),
    sa.Column('toler_in', sa.SmallInteger(), nullable=False),
    sa.Column('toler_out', sa.SmallInteger(), nullable=False),
    sa.Column('jadwal_kerja_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['jadwal_kerja_id'], ['jadwal_kerja.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grup_gaji_kom',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('use_kondisi', sa.Boolean(), nullable=False),
    sa.Column('kode_kondisi', sa.SmallInteger(), nullable=False),
    sa.Column('id_kondisi', sa.SmallInteger(), nullable=False),
    sa.Column('min_kondisi', sa.SmallInteger(), nullable=False),
    sa.Column('max_kondisi', sa.SmallInteger(), nullable=False),
    sa.Column('use_formula', sa.Boolean(), nullable=False),
    sa.Column('kode_formula', sa.SmallInteger(), nullable=False),
    sa.Column('id_formula', sa.SmallInteger(), nullable=False),
    sa.Column('operation_sum', sa.String(length=1), nullable=False),
    sa.Column('nilai_uang', sa.Numeric(precision=9, scale=2), nullable=False),
    sa.Column('hitung', sa.Enum('HARIAN', 'PERIODE', name='hitung'), nullable=False),
    sa.Column('grp_id', sa.UUID(), nullable=False),
    sa.Column('kom_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['grp_id'], ['grup_gaji.id'], ),
    sa.ForeignKeyConstraint(['kom_id'], ['komponen_gaji.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation_sum'),
    sa.UniqueConstraint('use_formula'),
    sa.UniqueConstraint('use_kondisi')
    )
    op.create_table('jatah_kuota_cuti',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.Column('data_karyawan_id', sa.UUID(), nullable=False),
    sa.Column('kuota_cuti_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['data_karyawan_id'], ['data_karyawan.id'], ),
    sa.ForeignKeyConstraint(['kuota_cuti_id'], ['kuota_cuti.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('grup_gaji_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('grup_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['grup_id'], ['grup_gaji.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    with op.batch_alter_table('data_karyawan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jabatan_id', sa.UUID(), nullable=False))
        batch_op.drop_constraint('data_karyawan_grup_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'jabatan', ['jabatan_id'], ['id'])
        batch_op.drop_column('jabatan')
        batch_op.drop_column('grup_id')

    with op.batch_alter_table('jadwal_kerja', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kode', sa.String(length=5), nullable=False))
        batch_op.drop_column('toler_out')
        batch_op.drop_column('time_out')
        batch_op.drop_column('toler_in')
        batch_op.drop_column('time_in')

    with op.batch_alter_table('kuota_cuti', schema=None) as batch_op:
        batch_op.drop_constraint('kuota_cuti_data_karyawan_id_fkey', type_='foreignkey')
        batch_op.drop_column('data_karyawan_id')

    op.drop_table('grup')
    op.drop_table('harga_gaji')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kuota_cuti', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_karyawan_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('kuota_cuti_data_karyawan_id_fkey', 'data_karyawan', ['data_karyawan_id'], ['id'])

    with op.batch_alter_table('jadwal_kerja', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_in', postgresql.TIME(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('toler_in', sa.SMALLINT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('time_out', postgresql.TIME(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('toler_out', sa.SMALLINT(), autoincrement=False, nullable=False))
        batch_op.drop_column('kode')

    with op.batch_alter_table('data_karyawan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grup_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('jabatan', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('data_karyawan_grup_id_fkey', 'grup', ['grup_id'], ['id'])
        batch_op.drop_column('jabatan_id')

    op.create_table('harga_gaji',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='harga_gaji_pkey'),
    sa.UniqueConstraint('key', name='harga_gaji_key_key')
    )
    op.create_table('grup',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nama', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='grup_pkey')
    )
    op.drop_table('grup_gaji_user')
    op.drop_table('jatah_kuota_cuti')
    op.drop_table('grup_gaji_kom')
    op.drop_table('detail_jadwal_kerja')
    op.drop_table('komponen_gaji')
    op.drop_table('jabatan')
    op.drop_table('grup_gaji')
    # ### end Alembic commands ###
