"""add date updted in riwayat penggajian

Revision ID: 17a252b6ff17
Revises: e086f8e33c9d
Create Date: 2025-08-14 23:23:20.978331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17a252b6ff17'
down_revision = 'e086f8e33c9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('riwayat_penggajian', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_updated', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('riwayat_penggajian', schema=None) as batch_op:
        batch_op.drop_column('date_updated')

    # ### end Alembic commands ###
