"""add history jadwal kerja

Revision ID: 1df7204044be
Revises: b0da6287f25e
Create Date: 2025-08-04 21:54:40.849002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1df7204044be'
down_revision = 'b0da6287f25e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('absensi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jadwal_time_in', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('jadwal_time_out', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('jadwal_toler_in', sa.SmallInteger(), nullable=True))
        batch_op.add_column(sa.Column('jadwal_toler_out', sa.SmallInteger(), nullable=True))
        batch_op.add_column(sa.Column('jadwal_kerja_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'jadwal_kerja', ['jadwal_kerja_id'], ['id'])

    with op.batch_alter_table('detail_absensi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('absensi_id', sa.UUID(), nullable=True))

    op.execute('UPDATE detail_absensi SET absensi_id = id_absensi')

    with op.batch_alter_table('detail_absensi', schema=None) as batch_op:
        batch_op.alter_column('absensi_id', nullable=False)
        batch_op.drop_constraint('detail_absensi_id_absensi_fkey', type_='foreignkey')
        batch_op.create_foreign_key('fk_detail_absensi_absensi_id', 'absensi', ['absensi_id'], ['id'])
        batch_op.drop_column('id_absensi')

    with op.batch_alter_table('jadwal_kerja', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
        batch_op.add_column(sa.Column('parent_schedule_id', sa.UUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_jadwal_kerja_is_active'), ['is_active'], unique=False)
        batch_op.create_foreign_key(None, 'jadwal_kerja', ['parent_schedule_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jadwal_kerja', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_jadwal_kerja_is_active'))
        batch_op.drop_column('parent_schedule_id')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('detail_absensi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_absensi', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('detail_absensi_id_absensi_fkey'), 'absensi', ['id_absensi'], ['id'])
        batch_op.drop_column('absensi_id')

    with op.batch_alter_table('absensi', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('jadwal_kerja_id')
        batch_op.drop_column('jadwal_toler_out')
        batch_op.drop_column('jadwal_toler_in')
        batch_op.drop_column('jadwal_time_out')
        batch_op.drop_column('jadwal_time_in')

    # ### end Alembic commands ###
