"""remove unique in column endpoint permission

Revision ID: 2439968a743e
Revises: b1e86bb53f5e
Create Date: 2025-08-01 14:57:23.821095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2439968a743e'
down_revision = 'b1e86bb53f5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('permission_endpoint_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('permission_endpoint_key'), ['endpoint'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
