"""add colum total in reimburse

Revision ID: 258b843a6ac1
Revises: 2ec68fd95c94
Create Date: 2025-07-31 14:05:40.369807

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision = '258b843a6ac1'
down_revision = '2ec68fd95c94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reimburse', schema=None) as batch_op:
        op.add_column('reimburse',
                      sa.Column('total', sa.NUMERIC(precision=9, scale=2), nullable=False, server_default=text('0')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reimburse', schema=None) as batch_op:
        batch_op.drop_column('total')

    # ### end Alembic commands ###
