"""add riwayat penggajian

Revision ID: 29bf8aed44fc
Revises: ae9b94e0efcb
Create Date: 2025-08-14 14:43:41.585373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29bf8aed44fc'
down_revision = 'ae9b94e0efcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('riwayat_penggajian',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('periode_start', sa.Date(), nullable=False),
    sa.Column('periode_end', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('total_karyawan', sa.Integer(), nullable=False),
    sa.Column('total_gaji_keseluruhan', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('grup_gaji_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['grup_gaji_id'], ['grup_gaji.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('riwayat_penggajian_detail',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('total_tunjangan', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_potongan', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('gaji', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('riwayat_penggajian_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['riwayat_penggajian_id'], ['riwayat_penggajian.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('riwayat_penggajian_rincian',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('komponen', sa.String(length=50), nullable=False),
    sa.Column('tipe', sa.String(length=20), nullable=False),
    sa.Column('jumlah', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('riwayat_penggajian_detail_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['riwayat_penggajian_detail_id'], ['riwayat_penggajian_detail.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('riwayat_penggajian_rincian')
    op.drop_table('riwayat_penggajian_detail')
    op.drop_table('riwayat_penggajian')
    # ### end Alembic commands ###
