"""grup gaji kom kode to string

Revision ID: 2be5111c2c8b
Revises: 4202c36d9f50
Create Date: 2025-08-11 23:19:10.036426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2be5111c2c8b'
down_revision = '4202c36d9f50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grup_gaji_kom', schema=None) as batch_op:
        batch_op.alter_column('kode_kondisi',
               existing_type=sa.SMALLINT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('kode_formula',
               existing_type=sa.SMALLINT(),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grup_gaji_kom', schema=None) as batch_op:
        batch_op.alter_column('kode_formula',
               existing_type=sa.String(length=50),
               type_=sa.SMALLINT(),
               existing_nullable=False)
        batch_op.alter_column('kode_kondisi',
               existing_type=sa.String(length=50),
               type_=sa.SMALLINT(),
               existing_nullable=False)

    # ### end Alembic commands ###
