"""add reminder log

Revision ID: 2fde299f2b98
Revises: c7636b8824e4
Create Date: 2025-08-23 15:05:05.963881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fde299f2b98'
down_revision = 'c7636b8824e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('reminder_type', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reminder_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reminder_log_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminder_log_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reminder_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_reminder_log_date'))

    op.drop_table('reminder_log')
    # ### end Alembic commands ###
