"""refactor is active in data karyawan not null

Revision ID: 355122c9b967
Revises: a89abd5133e9
Create Date: 2025-05-25 14:02:43.494975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '355122c9b967'
down_revision = 'a89abd5133e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_karyawan', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_karyawan', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
