"""delete grup gaji user

Revision ID: 37cb20bd23b1
Revises: 2be5111c2c8b
Create Date: 2025-08-12 13:29:35.654740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37cb20bd23b1'
down_revision = '2be5111c2c8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grup_gaji_user')
    with op.batch_alter_table('data_karyawan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grup_gaji_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'grup_gaji', ['grup_gaji_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_karyawan', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('grup_gaji_id')

    op.create_table('grup_gaji_user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('grup_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['grup_id'], ['grup_gaji.id'], name=op.f('grup_gaji_user_grup_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('grup_gaji_user_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('grup_gaji_user_pkey'))
    )
    # ### end Alembic commands ###
