"""change grup harga to uuid

Revision ID: 3b8418f92d2e
Revises: dc3c75d7206f
Create Date: 2025-06-24 21:44:38.065490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b8418f92d2e'
down_revision = 'dc3c75d7206f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('harga_harian_borongan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grup_id', sa.UUID(), nullable=True))
        batch_op.drop_column('grup_harga')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('harga_harian_borongan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grup_harga', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.drop_column('grup_id')

    # ### end Alembic commands ###
