"""init db

Revision ID: 410533dff2cb
Revises: 
Create Date: 2025-03-01 22:50:25.653688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '410533dff2cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_kontak',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alamat', sa.String(length=255), nullable=False),
    sa.Column('kota_kabupaten', sa.String(length=100), nullable=False),
    sa.Column('provinsi', sa.String(length=100), nullable=False),
    sa.Column('negara', sa.String(length=50), nullable=True),
    sa.Column('no_telepon', sa.String(length=20), nullable=True),
    sa.Column('nama_darurat', sa.String(length=150), nullable=True),
    sa.Column('no_telepon_darurat', sa.String(length=20), nullable=True),
    sa.Column('relasi_darurat', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_role',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('user_role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_role_id'], ['user_role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('user_role')
    op.drop_table('data_kontak')
    # ### end Alembic commands ###
