"""add table kode_perhitungan

Revision ID: 4202c36d9f50
Revises: 98927eec6117
Create Date: 2025-08-11 22:49:32.317488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4202c36d9f50'
down_revision = '98927eec6117'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kode_perhitungan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kode_perhitungan')
    # ### end Alembic commands ###
