"""change str to text data kontak

Revision ID: 474716626efc
Revises: 632b9e1f46de
Create Date: 2025-08-21 20:23:07.904275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '474716626efc'
down_revision = '632b9e1f46de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_kontak', schema=None) as batch_op:
        batch_op.alter_column('alamat',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('no_telepon',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('no_telepon_darurat',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_kontak', schema=None) as batch_op:
        batch_op.alter_column('no_telepon_darurat',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('no_telepon',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('alamat',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
