"""add durasi hari kerja di izin

Revision ID: 4d2b96499844
Revises: 1df7204044be
Create Date: 2025-08-05 13:52:26.060377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d2b96499844'
down_revision = '1df7204044be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('izin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('durasi_hari_kerja', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('izin', schema=None) as batch_op:
        batch_op.drop_column('durasi_hari_kerja')

    # ### end Alembic commands ###
