"""tambah precision untuk harga di reimburse

Revision ID: 50f90f64ec65
Revises: 258b843a6ac1
Create Date: 2025-07-31 14:35:03.236923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50f90f64ec65'
down_revision = '258b843a6ac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detail_reimburse', schema=None) as batch_op:
        batch_op.alter_column('harga',
               existing_type=sa.NUMERIC(precision=9, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('reimburse', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=sa.NUMERIC(precision=9, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reimburse', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=9, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('detail_reimburse', schema=None) as batch_op:
        batch_op.alter_column('harga',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=9, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###
