"""change datatype colum grup in harga harian

Revision ID: 51c3c7e6a184
Revises: ca9118c7480e
Create Date: 2025-06-22 21:47:03.674858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51c3c7e6a184'
down_revision = 'ca9118c7480e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('harga_harian_borongan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.alter_column('grup_harga',
               existing_type=sa.UUID(),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('harga_harian_borongan', schema=None) as batch_op:
        batch_op.alter_column('grup_harga',
               existing_type=sa.String(length=20),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
