"""updata table kom gaji

Revision ID: 541457db702e
Revises: 59f3a395fef6
Create Date: 2025-08-09 20:14:44.214781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '541457db702e'
down_revision = '59f3a395fef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('komponen_gaji', schema=None) as batch_op:
        batch_op.alter_column('kom_kode',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('komponen_gaji', schema=None) as batch_op:
        batch_op.alter_column('kom_kode',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)

    # ### end Alembic commands ###
