"""add FK created by riwayat penggajian

Revision ID: 564cb8e71439
Revises: 17a252b6ff17
Create Date: 2025-08-15 00:26:50.959218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '564cb8e71439'
down_revision = '17a252b6ff17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('riwayat_penggajian', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('riwayat_penggajian', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
