"""change grup gaji kom

Revision ID: 59f3a395fef6
Revises: f4e6c5dc1fbb
Create Date: 2025-08-09 14:57:45.077984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59f3a395fef6'
down_revision = 'f4e6c5dc1fbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grup_gaji_kom', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('grup_gaji_kom_operation_sum_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('grup_gaji_kom_use_formula_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('grup_gaji_kom_use_kondisi_key'), type_='unique')
        batch_op.drop_column('id_kondisi')
        batch_op.drop_column('id_formula')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grup_gaji_kom', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_formula', sa.SMALLINT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('id_kondisi', sa.SMALLINT(), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint(batch_op.f('grup_gaji_kom_use_kondisi_key'), ['use_kondisi'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('grup_gaji_kom_use_formula_key'), ['use_formula'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('grup_gaji_kom_operation_sum_key'), ['operation_sum'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
