"""remove embedding old kolom

Revision ID: 632b9e1f46de
Revises: d25774711285
Create Date: 2025-08-21 15:15:08.053535

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '632b9e1f46de'
down_revision = 'd25774711285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('face_embeddings', schema=None) as batch_op:
        batch_op.alter_column('embedding_data',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('embedding')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('face_embeddings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding', postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=True))
        batch_op.alter_column('embedding_data',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
