"""add cascade delete

Revision ID: 66860b39e214
Revises: 9fa75872383b
Create Date: 2025-08-18 21:32:27.033590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66860b39e214'
down_revision = '9fa75872383b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approval_absensi_borongan', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('approval_absensi_borongan_absensi_borongan_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'absensi_borongan', ['absensi_borongan_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('approval_izin', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('approval_izin_izin_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'izin', ['izin_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('approval_koreksi', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('approval_koreksi_absensi_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'absensi', ['absensi_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('approval_lembur', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('approval_lembur_lembur_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'lembur', ['lembur_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('approval_reimburse', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('approval_reimburse_reimburse_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'reimburse', ['reimburse_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('detail_absensi', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_detail_absensi_absensi_id'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'absensi', ['absensi_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('detail_approval_koreksi', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('detail_approval_koreksi_approval_koreksi_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'approval_koreksi', ['approval_koreksi_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('detail_reimburse', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('detail_reimburse_reimburse_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'reimburse', ['reimburse_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('riwayat_penggajian_detail', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('riwayat_penggajian_detail_riwayat_penggajian_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'riwayat_penggajian', ['riwayat_penggajian_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('riwayat_penggajian_rincian', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('riwayat_penggajian_rincian_riwayat_penggajian_detail_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'riwayat_penggajian_detail', ['riwayat_penggajian_detail_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('riwayat_penggajian_rincian', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('riwayat_penggajian_rincian_riwayat_penggajian_detail_id_fkey'), 'riwayat_penggajian_detail', ['riwayat_penggajian_detail_id'], ['id'])

    with op.batch_alter_table('riwayat_penggajian_detail', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('riwayat_penggajian_detail_riwayat_penggajian_id_fkey'), 'riwayat_penggajian', ['riwayat_penggajian_id'], ['id'])

    with op.batch_alter_table('detail_reimburse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('detail_reimburse_reimburse_id_fkey'), 'reimburse', ['reimburse_id'], ['id'])

    with op.batch_alter_table('detail_approval_koreksi', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('detail_approval_koreksi_approval_koreksi_id_fkey'), 'approval_koreksi', ['approval_koreksi_id'], ['id'])

    with op.batch_alter_table('detail_absensi', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_detail_absensi_absensi_id'), 'absensi', ['absensi_id'], ['id'])

    with op.batch_alter_table('approval_reimburse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('approval_reimburse_reimburse_id_fkey'), 'reimburse', ['reimburse_id'], ['id'])

    with op.batch_alter_table('approval_lembur', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('approval_lembur_lembur_id_fkey'), 'lembur', ['lembur_id'], ['id'])

    with op.batch_alter_table('approval_koreksi', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('approval_koreksi_absensi_id_fkey'), 'absensi', ['absensi_id'], ['id'])

    with op.batch_alter_table('approval_izin', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('approval_izin_izin_id_fkey'), 'izin', ['izin_id'], ['id'])

    with op.batch_alter_table('approval_absensi_borongan', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('approval_absensi_borongan_absensi_borongan_id_fkey'), 'absensi_borongan', ['absensi_borongan_id'], ['id'])

    # ### end Alembic commands ###
