"""change size column in detail absensi

Revision ID: 766c855fb55a
Revises: a38a68f5e457
Create Date: 2025-06-14 15:10:20.261595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '766c855fb55a'
down_revision = 'a38a68f5e457'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detail_absensi', schema=None) as batch_op:
        batch_op.alter_column('status_appv',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('status_absensi',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detail_absensi', schema=None) as batch_op:
        batch_op.alter_column('status_absensi',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.alter_column('status_appv',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
