"""move catatan to detail absensi from absensi

Revision ID: 7764938492ef
Revises: c98d08706c81
Create Date: 2025-06-14 14:49:22.366501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7764938492ef'
down_revision = 'c98d08706c81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('absensi', schema=None) as batch_op:
        batch_op.drop_column('catatan')

    with op.batch_alter_table('detail_absensi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('catatan', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detail_absensi', schema=None) as batch_op:
        batch_op.drop_column('catatan')

    with op.batch_alter_table('absensi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('catatan', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
