"""add is notif send in user

Revision ID: 77a20f2fd167
Revises: d9a7290eccb1
Create Date: 2025-06-09 19:50:13.584401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77a20f2fd167'
down_revision = 'd9a7290eccb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_notif_login_send', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_notif_login_send')

    # ### end Alembic commands ###
