"""refactor db jadwal

Revision ID: 782d66796e34
Revises: 603575939a4b
Create Date: 2025-03-09 21:49:00.809569

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '782d66796e34'
down_revision = '603575939a4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_pribadi', schema=None) as batch_op:
        batch_op.alter_column('tmpt_lahir',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)

    with op.batch_alter_table('jadwal_kerja', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_in', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('time_out', sa.Time(), nullable=False))
        batch_op.drop_column('jam_out')
        batch_op.drop_column('jam_in')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jadwal_kerja', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jam_in', postgresql.TIME(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('jam_out', postgresql.TIME(), autoincrement=False, nullable=False))
        batch_op.drop_column('time_out')
        batch_op.drop_column('time_in')

    with op.batch_alter_table('data_pribadi', schema=None) as batch_op:
        batch_op.alter_column('tmpt_lahir',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)

    # ### end Alembic commands ###
