"""add kuota cuti db

Revision ID: 78c528e5acf9
Revises: bbd1654e4edd
Create Date: 2025-03-03 21:54:45.059296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78c528e5acf9'
down_revision = 'bbd1654e4edd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kuota_cuti',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.Column('data_karyawan_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['data_karyawan_id'], ['data_karyawan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    sa.UniqueConstraint('value')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kuota_cuti')
    # ### end Alembic commands ###
