"""add column kode in user role

Revision ID: 83145715ae68
Revises: 355122c9b967
Create Date: 2025-05-25 14:40:47.084424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83145715ae68'
down_revision = '355122c9b967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kode', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_role', schema=None) as batch_op:
        batch_op.drop_column('kode')

    # ### end Alembic commands ###
