"""add db lembur, approval lembur, gaji dan sedikit penyesuaian

Revision ID: 860c2fd7b3fc
Revises: 78c528e5acf9
Create Date: 2025-03-04 22:20:34.732997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '860c2fd7b3fc'
down_revision = '78c528e5acf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('harga_gaji',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    sa.UniqueConstraint('value')
    )
    op.create_table('lembur',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('time_start', sa.Time(), nullable=False),
    sa.Column('time_end', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_lembur',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('approval_user_id', sa.UUID(), nullable=False),
    sa.Column('lembur_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['approval_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lembur_id'], ['lembur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_pribadi', schema=None) as batch_op:
        batch_op.drop_column('kewarganegaraan')
        batch_op.drop_column('pekerja_asing')

    with op.batch_alter_table('lokasi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('toleransi', sa.SmallInteger(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lokasi', schema=None) as batch_op:
        batch_op.drop_column('toleransi')

    with op.batch_alter_table('data_pribadi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pekerja_asing', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('kewarganegaraan', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    op.drop_table('approval_lembur')
    op.drop_table('lembur')
    op.drop_table('harga_gaji')
    # ### end Alembic commands ###
