"""refactor table jenis izin and kuota izin

Revision ID: 88bd75fd3e3a
Revises: ad81fa527edb
Create Date: 2025-07-25 16:14:16.104777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88bd75fd3e3a'
down_revision = 'ad81fa527edb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jatah_kuota_cuti', schema=None) as batch_op:
        batch_op.add_column(sa.Column('periode', sa.SmallInteger(), nullable=False))
        batch_op.add_column(sa.Column('kuota_awal', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('kuota_terpakai', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('sisa_kuota', sa.Integer(), nullable=False))
        batch_op.drop_column('year')
        batch_op.drop_column('izin_digunakan')
        batch_op.drop_column('kuota')

    with op.batch_alter_table('jenis_izin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kuota_default', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('periode_reset', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('berlaku_setelah_bulan', sa.Integer(), nullable=False))
        batch_op.drop_column('default_kuota')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jenis_izin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_kuota', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('berlaku_setelah_bulan')
        batch_op.drop_column('periode_reset')
        batch_op.drop_column('kuota_default')

    with op.batch_alter_table('jatah_kuota_cuti', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kuota', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('izin_digunakan', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('year', sa.SMALLINT(), autoincrement=False, nullable=False))
        batch_op.drop_column('sisa_kuota')
        batch_op.drop_column('kuota_terpakai')
        batch_op.drop_column('kuota_awal')
        batch_op.drop_column('periode')

    # ### end Alembic commands ###
