"""add cascade in detail abnsensi borongan

Revision ID: 9410cdedc7b3
Revises: c709200957d9
Create Date: 2025-07-07 21:43:01.043859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9410cdedc7b3'
down_revision = 'c709200957d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detail_absensi_borongan', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('detail_absensi_borongan_absensi_borongan_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'absensi_borongan', ['absensi_borongan_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detail_absensi_borongan', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('detail_absensi_borongan_absensi_borongan_id_fkey'), 'absensi_borongan', ['absensi_borongan_id'], ['id'])

    # ### end Alembic commands ###
