"""update table lembur

Revision ID: 969b35c2f1f4
Revises: 5cd2419456b7
Create Date: 2025-06-15 15:11:33.595575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '969b35c2f1f4'
down_revision = '5cd2419456b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lembur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keterangan', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lembur', schema=None) as batch_op:
        batch_op.drop_column('keterangan')

    # ### end Alembic commands ###
