"""add gaji pokok data keryawan

Revision ID: 98927eec6117
Revises: 541457db702e
Create Date: 2025-08-11 22:34:26.353262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98927eec6117'
down_revision = '541457db702e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_karyawan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gaji_pokok', sa.Numeric(precision=15, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_karyawan', schema=None) as batch_op:
        batch_op.drop_column('gaji_pokok')

    # ### end Alembic commands ###
