"""add column is active detail jadwal

Revision ID: 998af42bc843
Revises: e2c09fb8f68c
Create Date: 2025-07-24 10:56:32.757837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '998af42bc843'
down_revision = 'e2c09fb8f68c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detail_jadwal_kerja', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    with op.batch_alter_table('jadwal_kerja', schema=None) as batch_op:
        batch_op.drop_column('is_same_hour')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jadwal_kerja', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_same_hour', sa.BOOLEAN(), autoincrement=False, nullable=False))

    with op.batch_alter_table('detail_jadwal_kerja', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
