"""add face recog mode

Revision ID: 9fa75872383b
Revises: 046396b4b40e
Create Date: 2025-08-16 19:47:49.034260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fa75872383b'
down_revision = '046396b4b40e'
branch_labels = None
depends_on = None

enum_name = 'face_recog_mode'
enum_options = ('NORMAL', 'RENDAH', 'MATI')


def upgrade():
    sa.Enum(*enum_options, name=enum_name).create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_karyawan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('face_recognition_mode', sa.Enum(*enum_options, name=enum_name), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_karyawan', schema=None) as batch_op:
        batch_op.drop_column('face_recognition_mode')

    # ### end Alembic commands ###
