"""change time to datetime at table detail approval koreksi

Revision ID: a5d067508a9c
Revises: 998af42bc843
Create Date: 2025-07-25 13:22:19.418522

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a5d067508a9c'
down_revision = '998af42bc843'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detail_approval_koreksi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requested_datetime', sa.DateTime(), nullable=False))
        batch_op.drop_column('time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detail_approval_koreksi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', postgresql.TIME(), autoincrement=False, nullable=False))
        batch_op.drop_column('requested_datetime')

    # ### end Alembic commands ###
