"""add is active in data karyawan

Revision ID: a89abd5133e9
Revises: bb5b28b99d71
Create Date: 2025-05-25 14:01:39.780671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a89abd5133e9'
down_revision = 'bb5b28b99d71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_karyawan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_karyawan', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
