"""set nullable di absensi id table aproval koreksi

Revision ID: ad81fa527edb
Revises: a5d067508a9c
Create Date: 2025-07-25 14:47:05.361294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad81fa527edb'
down_revision = 'a5d067508a9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approval_koreksi', schema=None) as batch_op:
        batch_op.alter_column('absensi_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approval_koreksi', schema=None) as batch_op:
        batch_op.alter_column('absensi_id',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###
