"""add colum tgl resign di data karyawan

Revision ID: ae9b94e0efcb
Revises: 075f83ce0a0e
Create Date: 2025-08-13 23:58:01.734309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae9b94e0efcb'
down_revision = '075f83ce0a0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_karyawan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tgl_resign', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_karyawan', schema=None) as batch_op:
        batch_op.drop_column('tgl_resign')

    # ### end Alembic commands ###
