"""add created by absensi borongan

Revision ID: b0da6287f25e
Revises: 2439968a743e
Create Date: 2025-08-02 23:12:46.758404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0da6287f25e'
down_revision = '2439968a743e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('absensi_borongan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.UUID(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('absensi_borongan', schema=None) as batch_op:
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
