"""add column endpoint in table perimission

Revision ID: b1e86bb53f5e
Revises: 9c6d42cbb24a
Create Date: 2025-08-01 13:28:59.699226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1e86bb53f5e'
down_revision = '9c6d42cbb24a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endpoint', sa.String(length=200), nullable=True))
        batch_op.create_unique_constraint(None, ['endpoint'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('endpoint')

    # ### end Alembic commands ###
