"""add table route

Revision ID: bb5b28b99d71
Revises: 40533fc0d083
Create Date: 2025-05-25 12:14:34.048586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb5b28b99d71'
down_revision = '40533fc0d083'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('component', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('parent', sa.String(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routes')
    # ### end Alembic commands ###
