"""edit table harga harian

Revision ID: c0182724a7c3
Revises: fdd98899812c
Create Date: 2025-08-25 20:41:24.269487

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c0182724a7c3'
down_revision = 'fdd98899812c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('harga_harian_borongan', schema=None) as batch_op:
        batch_op.alter_column('harga_normal',
               existing_type=sa.NUMERIC(precision=9, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
        batch_op.drop_column('grup_id')
        batch_op.drop_column('jam_start_normal')
        batch_op.drop_column('harga_lembur')
        batch_op.drop_column('toleransi_waktu')
        batch_op.drop_column('jam_end_normal')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('harga_harian_borongan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jam_end_normal', postgresql.TIME(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('toleransi_waktu', sa.SMALLINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('harga_lembur', sa.NUMERIC(precision=9, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('jam_start_normal', postgresql.TIME(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('grup_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.alter_column('harga_normal',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=9, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###
