"""add user pic

Revision ID: c2a441460085
Revises: d0f797bed937
Create Date: 2025-06-09 12:11:25.495792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2a441460085'
down_revision = 'd0f797bed937'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_karyawan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_pic_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_pic_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_karyawan', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_pic_id')

    # ### end Alembic commands ###
