"""remove kolom hitung di gaji

Revision ID: c34e37aa0cfe
Revises: 564cb8e71439
Create Date: 2025-08-15 19:42:58.570062

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c34e37aa0cfe'
down_revision = '564cb8e71439'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grup_gaji_kom', schema=None) as batch_op:
        batch_op.drop_column('hitung')

    with op.batch_alter_table('komponen_gaji', schema=None) as batch_op:
        batch_op.drop_column('hitung')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('komponen_gaji', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hitung', postgresql.ENUM('HARIAN', 'PERIODE', name='hitung_kom_gaji'), autoincrement=False, nullable=False))

    with op.batch_alter_table('grup_gaji_kom', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hitung', postgresql.ENUM('HARIAN', 'PERIODE', name='hitung'), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
