"""complete DB

Revision ID: c3af6b3686c9
Revises: ecc40141d425
Create Date: 2025-03-02 21:28:57.945181

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c3af6b3686c9'
down_revision = 'ecc40141d425'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('face_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('embedding', postgresql.ARRAY(sa.Float()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jenis_izin',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('absensi',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('lokasi', sa.String(length=50), nullable=False),
    sa.Column('metode', sa.String(length=30), nullable=False),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('izin',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('tgl_izin', sa.Date(), nullable=False),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('jenis_izin_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['jenis_izin_id'], ['jenis_izin.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_izin',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('approval_user_id', sa.UUID(), nullable=False),
    sa.Column('izin_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['approval_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['izin_id'], ['izin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_kehadiran',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('approval_user_id', sa.UUID(), nullable=False),
    sa.Column('absensi_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['absensi_id'], ['absensi.id'], ),
    sa.ForeignKeyConstraint(['approval_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detail_absensi',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('status_appv', sa.String(length=10), nullable=False),
    sa.Column('status_absensi', sa.String(length=10), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('id_absensi', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id_absensi'], ['absensi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_koreksi',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('approval_user_id', sa.UUID(), nullable=False),
    sa.Column('detail_absensi_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['approval_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['detail_absensi_id'], ['detail_absensi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('face_embedding_id', sa.UUID(), nullable=False))
        batch_op.create_foreign_key(None, 'face_embeddings', ['face_embedding_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('face_embedding_id')

    op.drop_table('approval_koreksi')
    op.drop_table('detail_absensi')
    op.drop_table('approval_kehadiran')
    op.drop_table('approval_izin')
    op.drop_table('izin')
    op.drop_table('absensi')
    op.drop_table('jenis_izin')
    op.drop_table('face_embeddings')
    # ### end Alembic commands ###
