"""add status to absensi borongan

Revision ID: c709200957d9
Revises: 3b8418f92d2e
Create Date: 2025-07-06 13:52:19.666339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c709200957d9'
down_revision = '3b8418f92d2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('absensi_borongan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=30), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('absensi_borongan', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
