"""fix change nullable in table user

Revision ID: c70e78ee621a
Revises: 1500e835d1b2
Create Date: 2025-03-09 15:55:34.407230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c70e78ee621a'
down_revision = '1500e835d1b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lokasi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('user_role_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('data_kontak_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('data_pribadi_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('data_karyawan_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('face_embedding_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('face_embedding_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('data_karyawan_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('data_pribadi_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('data_kontak_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('user_role_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('lokasi', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
