"""change phone to text

Revision ID: c7636b8824e4
Revises: dd1b831f0490
Create Date: 2025-08-21 21:54:07.962808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7636b8824e4'
down_revision = 'dd1b831f0490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)

    # ### end Alembic commands ###
