"""ad column description in libur

Revision ID: c98d08706c81
Revises: f36326bb27ab
Create Date: 2025-06-13 22:43:05.309235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c98d08706c81'
down_revision = 'f36326bb27ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libur', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
