"""edit table perusahaan

Revision ID: cbeb23e91e47
Revises: d12ba776b210
Create Date: 2025-07-12 21:21:40.762840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbeb23e91e47'
down_revision = 'd12ba776b210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perusahaan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nama', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('created_by', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('date_updated', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_by', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perusahaan', schema=None) as batch_op:
        batch_op.drop_column('updated_by')
        batch_op.drop_column('date_updated')
        batch_op.drop_column('created_by')
        batch_op.drop_column('date_created')
        batch_op.drop_column('nama')

    # ### end Alembic commands ###
