"""update izin to save start to end date izin

Revision ID: ce720b25ae1d
Revises: d968e45c2d4d
Create Date: 2025-06-15 12:14:56.839467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce720b25ae1d'
down_revision = 'd968e45c2d4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('izin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tgl_izin_start', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('tgl_izin_end', sa.Date(), nullable=False))
        batch_op.drop_column('tgl_izin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('izin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tgl_izin', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.drop_column('tgl_izin_end')
        batch_op.drop_column('tgl_izin_start')

    # ### end Alembic commands ###
