"""add db kontak, pribadi, karyawan

Revision ID: d06334b6c749
Revises: 410533dff2cb
Create Date: 2025-03-01 23:24:28.515104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd06334b6c749'
down_revision = '410533dff2cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_karyawan',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nip', sa.String(length=18), nullable=False),
    sa.Column('tgl_gabung', sa.Date(), nullable=False),
    sa.Column('lokasi_kerja', sa.String(length=150), nullable=False),
    sa.Column('tipe_karyawan', sa.String(length=30), nullable=True),
    sa.Column('jabatan', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_pribadi',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('tgl_lahir', sa.Date(), nullable=False),
    sa.Column('tmpt_lahir', sa.String(length=150), nullable=False),
    sa.Column('status_kawin', sa.String(length=20), nullable=True),
    sa.Column('agama', sa.String(length=30), nullable=True),
    sa.Column('gol_darah', sa.String(length=3), nullable=True),
    sa.Column('pekerja_asing', sa.Boolean(), nullable=False),
    sa.Column('kewarganegaraan', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_kontak_id', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('data_pribadi_id', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('data_karyawan_id', sa.UUID(), nullable=False))
        batch_op.create_foreign_key(None, 'data_karyawan', ['data_karyawan_id'], ['id'])
        batch_op.create_foreign_key(None, 'data_kontak', ['data_kontak_id'], ['id'])
        batch_op.create_foreign_key(None, 'data_pribadi', ['data_pribadi_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('data_karyawan_id')
        batch_op.drop_column('data_pribadi_id')
        batch_op.drop_column('data_kontak_id')

    op.drop_table('data_pribadi')
    op.drop_table('data_karyawan')
    # ### end Alembic commands ###
