"""add updated log in pengumuman

Revision ID: d12ba776b210
Revises: 9410cdedc7b3
Create Date: 2025-07-10 22:38:46.608355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd12ba776b210'
down_revision = '9410cdedc7b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pengumuman', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_updated', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_by', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pengumuman', schema=None) as batch_op:
        batch_op.drop_column('updated_by')
        batch_op.drop_column('date_updated')

    # ### end Alembic commands ###
