"""riwayat penggajian total jadi text

Revision ID: d213718ffbc8
Revises: 214d20e7bd36
Create Date: 2025-09-02 14:39:56.686321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd213718ffbc8'
down_revision = '214d20e7bd36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('riwayat_penggajian', schema=None) as batch_op:
        batch_op.alter_column('total_gaji_keseluruhan',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('riwayat_penggajian', schema=None) as batch_op:
        batch_op.alter_column('total_gaji_keseluruhan',
               existing_type=sa.Text(),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###
