"""add kolom embedding data 

Revision ID: d25774711285
Revises: 789f8f351624
Create Date: 2025-08-21 14:54:48.186020

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd25774711285'
down_revision = '789f8f351624'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('face_embeddings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding_data', sa.Text(), nullable=True))
        batch_op.alter_column('embedding',
               existing_type=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('face_embeddings', schema=None) as batch_op:
        batch_op.alter_column('embedding',
               existing_type=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               nullable=False)
        batch_op.drop_column('embedding_data')

    # ### end Alembic commands ###
