"""update detail approval koreksi add catatan

Revision ID: d28fd6b63169
Revises: 0583721a4231
Create Date: 2025-06-14 23:32:31.335379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd28fd6b63169'
down_revision = '0583721a4231'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approval_koreksi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('catatan_pengajuan', sa.Text(), nullable=False))

    with op.batch_alter_table('detail_approval_koreksi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('type', sa.String(), nullable=False))
        batch_op.drop_constraint(batch_op.f('detail_approval_koreksi_detail_absensi_id_fkey'), type_='foreignkey')
        batch_op.drop_column('detail_absensi_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detail_approval_koreksi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detail_absensi_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('detail_approval_koreksi_detail_absensi_id_fkey'), 'detail_absensi', ['detail_absensi_id'], ['id'])
        batch_op.drop_column('type')
        batch_op.drop_column('time')

    with op.batch_alter_table('approval_koreksi', schema=None) as batch_op:
        batch_op.drop_column('catatan_pengajuan')

    # ### end Alembic commands ###
