"""add table detail reimburse

Revision ID: d53a0379a867
Revises: cbeb23e91e47
Create Date: 2025-07-13 20:15:12.136996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd53a0379a867'
down_revision = 'cbeb23e91e47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detail_reimburse',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nama', sa.String(length=255), nullable=False),
    sa.Column('harga', sa.Numeric(precision=9, scale=2), nullable=False),
    sa.Column('jumlah', sa.Integer(), nullable=False),
    sa.Column('reimburse_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['reimburse_id'], ['reimburse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detail_reimburse')
    # ### end Alembic commands ###
