"""update table izin

Revision ID: db0971fc2d22
Revises: d4a31809c13c
Create Date: 2025-06-15 15:05:07.265571

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'db0971fc2d22'
down_revision = 'd4a31809c13c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lembur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_start', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('date_end', sa.DateTime(), nullable=False))
        batch_op.drop_column('time_start')
        batch_op.drop_column('time_end')
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lembur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('time_end', postgresql.TIME(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('time_start', postgresql.TIME(), autoincrement=False, nullable=False))
        batch_op.drop_column('date_end')
        batch_op.drop_column('date_start')

    # ### end Alembic commands ###
