"""change tgl_lahir to text

Revision ID: dd1b831f0490
Revises: 474716626efc
Create Date: 2025-08-21 21:47:32.826083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd1b831f0490'
down_revision = '474716626efc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_pribadi', schema=None) as batch_op:
        batch_op.alter_column('tgl_lahir',
               existing_type=sa.DATE(),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_pribadi', schema=None) as batch_op:
        batch_op.alter_column('tgl_lahir',
               existing_type=sa.Text(),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
