"""add is paid in jenis izin

Revision ID: e086f8e33c9d
Revises: 29bf8aed44fc
Create Date: 2025-08-14 21:50:20.944260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e086f8e33c9d'
down_revision = '29bf8aed44fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jenis_izin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_paid', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jenis_izin', schema=None) as batch_op:
        batch_op.drop_column('is_paid')

    # ### end Alembic commands ###
