"""empty message

Revision ID: e2c09fb8f68c
Revises: 
Create Date: 2025-07-23 15:47:04.943696

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e2c09fb8f68c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('absensi_borongan',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('total', sa.Numeric(precision=9, scale=2), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('config_props',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('grup_gaji',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('grup_kode', sa.String(length=5), nullable=False),
    sa.Column('grup_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grup_kode')
    )
    op.create_table('harga_harian_borongan',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('harga_normal', sa.Numeric(precision=9, scale=2), nullable=False),
    sa.Column('harga_lembur', sa.Numeric(precision=9, scale=2), nullable=False),
    sa.Column('jam_start_normal', sa.Time(), nullable=True),
    sa.Column('jam_end_normal', sa.Time(), nullable=True),
    sa.Column('toleransi_waktu', sa.SmallInteger(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('grup_id', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jabatan',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nama', sa.String(length=50), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['jabatan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jadwal_kerja',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kode', sa.String(length=5), nullable=False),
    sa.Column('shift', sa.String(length=50), nullable=False),
    sa.Column('is_same_hour', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jenis_izin',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('default_kuota', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('komponen_gaji',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kom_kode', sa.String(length=5), nullable=False),
    sa.Column('kom_name', sa.String(length=100), nullable=False),
    sa.Column('no_urut', sa.SmallInteger(), nullable=False),
    sa.Column('tipe', sa.Enum('TUNJANGAN', 'POTONGAN', name='tipe_kom_gaji'), nullable=False),
    sa.Column('hitung', sa.Enum('HARIAN', 'PERIODE', name='hitung_kom_gaji'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('libur',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_holiday', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lokasi',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('toleransi', sa.SmallInteger(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pengumuman',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('judul', sa.String(length=50), nullable=False),
    sa.Column('isi', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('perusahaan',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nama', sa.String(length=255), nullable=False),
    sa.Column('alamat', sa.String(length=255), nullable=False),
    sa.Column('kota_kabupaten', sa.String(length=100), nullable=False),
    sa.Column('provinsi', sa.String(length=100), nullable=False),
    sa.Column('negara', sa.String(length=50), nullable=True),
    sa.Column('no_telepon', sa.String(length=20), nullable=True),
    sa.Column('kode_pos', sa.String(length=10), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('mimetype', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('component', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('parent', sa.String(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_role',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('kode', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detail_jadwal_kerja',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hari', sa.Enum('SENIN', 'SELASA', 'RABU', 'KAMIS', 'JUMAT', 'SABTU', 'MINGGU', name='hari'), nullable=False),
    sa.Column('time_in', sa.Time(), nullable=False),
    sa.Column('time_out', sa.Time(), nullable=False),
    sa.Column('toler_in', sa.SmallInteger(), nullable=False),
    sa.Column('toler_out', sa.SmallInteger(), nullable=False),
    sa.Column('jadwal_kerja_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['jadwal_kerja_id'], ['jadwal_kerja.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grup_gaji_kom',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('use_kondisi', sa.Boolean(), nullable=False),
    sa.Column('kode_kondisi', sa.SmallInteger(), nullable=False),
    sa.Column('id_kondisi', sa.SmallInteger(), nullable=False),
    sa.Column('min_kondisi', sa.SmallInteger(), nullable=False),
    sa.Column('max_kondisi', sa.SmallInteger(), nullable=False),
    sa.Column('use_formula', sa.Boolean(), nullable=False),
    sa.Column('kode_formula', sa.SmallInteger(), nullable=False),
    sa.Column('id_formula', sa.SmallInteger(), nullable=False),
    sa.Column('operation_sum', sa.String(length=1), nullable=False),
    sa.Column('nilai_uang', sa.Numeric(precision=9, scale=2), nullable=False),
    sa.Column('hitung', sa.Enum('HARIAN', 'PERIODE', name='hitung'), nullable=False),
    sa.Column('grp_id', sa.UUID(), nullable=False),
    sa.Column('kom_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['grp_id'], ['grup_gaji.id'], ),
    sa.ForeignKeyConstraint(['kom_id'], ['komponen_gaji.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation_sum'),
    sa.UniqueConstraint('use_formula'),
    sa.UniqueConstraint('use_kondisi')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fullname', sa.String(length=80), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('phone', sa.String(length=16), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('is_face_registration_required', sa.Boolean(), nullable=True),
    sa.Column('is_notif_login_send', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('user_role_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_role_id'], ['user_role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('absensi',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('lokasi', sa.String(length=50), nullable=False),
    sa.Column('metode', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_absensi_borongan',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('approval_user_id', sa.UUID(), nullable=False),
    sa.Column('absensi_borongan_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['absensi_borongan_id'], ['absensi_borongan.id'], ),
    sa.ForeignKeyConstraint(['approval_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_karyawan',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nip', sa.String(length=8), nullable=False),
    sa.Column('tgl_gabung', sa.Date(), nullable=False),
    sa.Column('tipe_karyawan', sa.String(length=30), nullable=True),
    sa.Column('lokasi_id', sa.UUID(), nullable=False),
    sa.Column('jadwal_kerja_id', sa.UUID(), nullable=False),
    sa.Column('jabatan_id', sa.UUID(), nullable=False),
    sa.Column('user_pic_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['jabatan_id'], ['jabatan.id'], ),
    sa.ForeignKeyConstraint(['jadwal_kerja_id'], ['jadwal_kerja.id'], ),
    sa.ForeignKeyConstraint(['lokasi_id'], ['lokasi.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_pic_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('data_kontak',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alamat', sa.String(length=255), nullable=False),
    sa.Column('no_telepon', sa.String(length=20), nullable=True),
    sa.Column('nama_darurat', sa.String(length=150), nullable=True),
    sa.Column('no_telepon_darurat', sa.String(length=20), nullable=True),
    sa.Column('relasi_darurat', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('data_pribadi',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('tgl_lahir', sa.Date(), nullable=False),
    sa.Column('tmpt_lahir', sa.String(length=150), nullable=True),
    sa.Column('status_kawin', sa.String(length=20), nullable=True),
    sa.Column('agama', sa.String(length=30), nullable=True),
    sa.Column('gol_darah', sa.String(length=3), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('detail_absensi_borongan',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ton_normal', sa.Numeric(precision=9, scale=2), nullable=False),
    sa.Column('ton_lembur', sa.Numeric(precision=9, scale=2), nullable=False),
    sa.Column('tipe', sa.String(length=20), nullable=False),
    sa.Column('total', sa.Numeric(precision=9, scale=2), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('absensi_borongan_id', sa.UUID(), nullable=False),
    sa.Column('harga_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['absensi_borongan_id'], ['absensi_borongan.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['harga_id'], ['harga_harian_borongan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('face_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('embedding', postgresql.ARRAY(sa.Float()), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grup_gaji_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('grup_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['grup_id'], ['grup_gaji.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('izin',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('tgl_izin_start', sa.Date(), nullable=False),
    sa.Column('tgl_izin_end', sa.Date(), nullable=False),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('jenis_izin_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['jenis_izin_id'], ['jenis_izin.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jatah_kuota_cuti',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('kuota', sa.Integer(), nullable=False),
    sa.Column('izin_digunakan', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('jenis_izin_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['jenis_izin_id'], ['jenis_izin.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lembur',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date_start', sa.DateTime(), nullable=False),
    sa.Column('date_end', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('keterangan', sa.Text(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reimburse',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('photo_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['photo_id'], ['photo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_login_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_izin',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('approval_user_id', sa.UUID(), nullable=False),
    sa.Column('izin_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['approval_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['izin_id'], ['izin.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_koreksi',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('absensi_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('catatan_pengajuan', sa.Text(), nullable=True),
    sa.Column('approval_user_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('absensi_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['absensi_id'], ['absensi.id'], ),
    sa.ForeignKeyConstraint(['approval_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_lembur',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('approval_user_id', sa.UUID(), nullable=False),
    sa.Column('lembur_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['approval_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lembur_id'], ['lembur.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_reimburse',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('approval_user_id', sa.UUID(), nullable=False),
    sa.Column('reimburse_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['approval_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reimburse_id'], ['reimburse.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detail_absensi',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('status_appv', sa.String(length=20), nullable=False),
    sa.Column('status_absensi', sa.String(length=20), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('id_absensi', sa.UUID(), nullable=False),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_absensi'], ['absensi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detail_reimburse',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nama', sa.String(length=255), nullable=False),
    sa.Column('harga', sa.Numeric(precision=9, scale=2), nullable=False),
    sa.Column('jumlah', sa.Integer(), nullable=False),
    sa.Column('reimburse_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['reimburse_id'], ['reimburse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detail_approval_koreksi',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('approval_koreksi_id', sa.UUID(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['approval_koreksi_id'], ['approval_koreksi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detail_approval_koreksi')
    op.drop_table('detail_reimburse')
    op.drop_table('detail_absensi')
    op.drop_table('approval_reimburse')
    op.drop_table('approval_lembur')
    op.drop_table('approval_koreksi')
    op.drop_table('approval_izin')
    op.drop_table('user_login_log')
    op.drop_table('reimburse')
    op.drop_table('lembur')
    op.drop_table('jatah_kuota_cuti')
    op.drop_table('izin')
    op.drop_table('grup_gaji_user')
    op.drop_table('face_embeddings')
    op.drop_table('detail_absensi_borongan')
    op.drop_table('data_pribadi')
    op.drop_table('data_kontak')
    op.drop_table('data_karyawan')
    op.drop_table('approval_absensi_borongan')
    op.drop_table('absensi')
    op.drop_table('users')
    op.drop_table('grup_gaji_kom')
    op.drop_table('detail_jadwal_kerja')
    op.drop_table('user_role')
    op.drop_table('routes')
    op.drop_table('photo')
    op.drop_table('perusahaan')
    op.drop_table('pengumuman')
    op.drop_table('lokasi')
    op.drop_table('libur')
    op.drop_table('komponen_gaji')
    op.drop_table('jenis_izin')
    op.drop_table('jadwal_kerja')
    op.drop_table('jabatan')
    op.drop_table('harga_harian_borongan')
    op.drop_table('grup_gaji')
    op.drop_table('config_props')
    op.drop_table('absensi_borongan')
    # ### end Alembic commands ###
