"""add column is same hour jadwal kerja

Revision ID: e63a93e85c4c
Revises: 612d08005087
Create Date: 2025-04-28 22:17:53.141389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e63a93e85c4c'
down_revision = '612d08005087'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jadwal_kerja', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_same_hour', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jadwal_kerja', schema=None) as batch_op:
        batch_op.drop_column('is_same_hour')

    # ### end Alembic commands ###
