"""add nilai dinamis grup gaji

Revision ID: e67687b0c757
Revises: c34e37aa0cfe
Create Date: 2025-08-15 22:19:58.524137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e67687b0c757'
down_revision = 'c34e37aa0cfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grup_gaji_kom', schema=None) as batch_op:
        batch_op.add_column(sa.Column('use_nilai_dinamis', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('kode_nilai_dinamis', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('nilai_statis', sa.Numeric(precision=15, scale=2), nullable=True))
        batch_op.alter_column('kode_kondisi',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('min_kondisi',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               nullable=True)
        batch_op.alter_column('max_kondisi',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               nullable=True)
        batch_op.alter_column('kode_formula',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('nilai_uang')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grup_gaji_kom', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nilai_uang', sa.NUMERIC(precision=9, scale=2), autoincrement=False, nullable=False))
        batch_op.alter_column('kode_formula',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('max_kondisi',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               nullable=False)
        batch_op.alter_column('min_kondisi',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               nullable=False)
        batch_op.alter_column('kode_kondisi',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('nilai_statis')
        batch_op.drop_column('kode_nilai_dinamis')
        batch_op.drop_column('use_nilai_dinamis')

    # ### end Alembic commands ###
