"""add table reimburse, lokasi, libur, jk, photo, perusahaan, grup

Revision ID: ecc40141d425
Revises: d06334b6c749
Create Date: 2025-03-02 14:22:46.372748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecc40141d425'
down_revision = 'd06334b6c749'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grup',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nama', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jadwal_kerja',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shift', sa.String(length=50), nullable=False),
    sa.Column('jam_in', sa.Time(), nullable=False),
    sa.Column('jam_out', sa.Time(), nullable=False),
    sa.Column('toler_in', sa.SmallInteger(), nullable=False),
    sa.Column('toler_out', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('libur',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_holiday', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lokasi',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nama', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('perusahaan',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alamat', sa.String(length=255), nullable=False),
    sa.Column('kota_kabupaten', sa.String(length=100), nullable=False),
    sa.Column('provinsi', sa.String(length=100), nullable=False),
    sa.Column('negara', sa.String(length=50), nullable=True),
    sa.Column('no_telepon', sa.String(length=20), nullable=True),
    sa.Column('kode_pos', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reimburse',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nama', sa.String(length=255), nullable=False),
    sa.Column('jumlah', sa.Numeric(precision=9, scale=2), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('photo_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['photo_id'], ['photo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_login_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_reimburse',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('approval_user_id', sa.UUID(), nullable=False),
    sa.Column('reimburse_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['approval_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reimburse_id'], ['reimburse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_karyawan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lokasi_id', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('jadwal_kerja_id', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('grup_id', sa.UUID(), nullable=False))
        batch_op.create_foreign_key(None, 'grup', ['grup_id'], ['id'])
        batch_op.create_foreign_key(None, 'jadwal_kerja', ['jadwal_kerja_id'], ['id'])
        batch_op.create_foreign_key(None, 'lokasi', ['lokasi_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_karyawan', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('grup_id')
        batch_op.drop_column('jadwal_kerja_id')
        batch_op.drop_column('lokasi_id')

    op.drop_table('approval_reimburse')
    op.drop_table('user_login_log')
    op.drop_table('reimburse')
    op.drop_table('photo')
    op.drop_table('perusahaan')
    op.drop_table('lokasi')
    op.drop_table('libur')
    op.drop_table('jadwal_kerja')
    op.drop_table('grup')
    # ### end Alembic commands ###
