"""approval koreksi status length update and catatan nullable

Revision ID: ef5534e8cae6
Revises: d28fd6b63169
Create Date: 2025-06-14 23:52:27.207433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef5534e8cae6'
down_revision = 'd28fd6b63169'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approval_koreksi', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=30),
               existing_nullable=False)
        batch_op.alter_column('catatan_pengajuan',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approval_koreksi', schema=None) as batch_op:
        batch_op.alter_column('catatan_pengajuan',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
