"""update nullable in harga

Revision ID: f3557a0a7eb2
Revises: fca5883a888b
Create Date: 2025-06-23 22:45:01.496886

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f3557a0a7eb2'
down_revision = 'fca5883a888b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('harga_harian_borongan', schema=None) as batch_op:
        batch_op.alter_column('jam_start_normal',
               existing_type=postgresql.TIME(),
               nullable=True)
        batch_op.alter_column('jam_end_normal',
               existing_type=postgresql.TIME(),
               nullable=True)
        batch_op.alter_column('toleransi_waktu',
               existing_type=sa.SMALLINT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('harga_harian_borongan', schema=None) as batch_op:
        batch_op.alter_column('toleransi_waktu',
               existing_type=sa.SMALLINT(),
               nullable=False)
        batch_op.alter_column('jam_end_normal',
               existing_type=postgresql.TIME(),
               nullable=False)
        batch_op.alter_column('jam_start_normal',
               existing_type=postgresql.TIME(),
               nullable=False)

    # ### end Alembic commands ###
