"""change Fk face embedd

Revision ID: f36326bb27ab
Revises: 77a20f2fd167
Create Date: 2025-06-10 21:59:37.087868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f36326bb27ab'
down_revision = '77a20f2fd167'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('face_embeddings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.UUID(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_face_embedding_id_fkey', type_='foreignkey')
        batch_op.drop_column('face_embedding_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('face_embedding_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('users_face_embedding_id_fkey', 'face_embeddings', ['face_embedding_id'], ['id'])

    with op.batch_alter_table('face_embeddings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
