"""add nullable in jadwal kerja user untuk user borongan

Revision ID: f4e6c5dc1fbb
Revises: 4d2b96499844
Create Date: 2025-08-05 14:13:02.195032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4e6c5dc1fbb'
down_revision = '4d2b96499844'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_karyawan', schema=None) as batch_op:
        batch_op.alter_column('jadwal_kerja_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_karyawan', schema=None) as batch_op:
        batch_op.alter_column('jadwal_kerja_id',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###
