"""edit table photo

Revision ID: f80df96da679
Revises: d53a0379a867
Create Date: 2025-07-13 20:49:23.024295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f80df96da679'
down_revision = 'd53a0379a867'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('mimetype', sa.String(length=255), nullable=False))
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)

    with op.batch_alter_table('reimburse', schema=None) as batch_op:
        batch_op.drop_column('jumlah')
        batch_op.drop_column('nama')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reimburse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nama', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('jumlah', sa.NUMERIC(precision=9, scale=2), autoincrement=False, nullable=False))

    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.drop_column('mimetype')
        batch_op.drop_column('filename')

    # ### end Alembic commands ###
