"""add colum type in harga

Revision ID: fca5883a888b
Revises: 51c3c7e6a184
Create Date: 2025-06-23 22:41:55.220711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fca5883a888b'
down_revision = '51c3c7e6a184'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('harga_harian_borongan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('harga_harian_borongan', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
