"""lebar kolom gol_darah

Revision ID: fdd98899812c
Revises: d3b19dfd4c95
Create Date: 2025-08-24 21:13:01.925338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdd98899812c'
down_revision = 'd3b19dfd4c95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_pribadi', schema=None) as batch_op:
        batch_op.alter_column('gol_darah',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_pribadi', schema=None) as batch_op:
        batch_op.alter_column('gol_darah',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=3),
               existing_nullable=True)

    # ### end Alembic commands ###
