from .users import Users
from .user_role import UserRole
from .data_kontak import DataKontak
from .data_pribadi import DataPribadi
from .data_karyawan import DataKaryawan
from .jadwal_kerja import JadwalKerja
from .detail_jadwal_kerja import DetailJadwalKerja
from .lokasi import Lokasi
from .perusahaan import Perusahaan
from .jabatan import Jabatan
from .user_login_log import UserLoginLog
from .libur import Libur
from .reimburse import Reimburse
from .photo import Photo
from .approval_reimburse import ApprovalReimburse
from .izin import Izin
from .jenis_izin import JenisIzin
from .approval_izin import ApprovalIzin
from .absensi import Absensi
from .detail_absensi import DetailAbsensi
from .approval_koreksi import ApprovalKoreksi
from .face_embeddings import FaceEmbeddings
from .config_props import ConfigProps
from .kuota_cuti import KuotaCuti
from .lembur import Lembur
from .approval_lembur import ApprovalLembur
from .pengumuman import Pengumuman
from .komponen_gaji import KomponenGaji
from .grup_gaji import GrupGaji
from .grup_gaji_kom import GrupGajiKom
from .grup_gaji_user import GrupGajiUser
from .jatah_kuota_cuti import JatahKuotaCuti
from .routes import Route